name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ github.actor }}
      PAT: ${{ secrets.PAT }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5
      
    - name: Authenticate to GitHub packages
      run: dotnet nuget add source --username ${USERNAME} --password ${PAT} --store-password-in-clear-text --name "PrimeService 0.1.0" "https://nuget.pkg.github.com/Zina-420001498/index.json"
      
    #- name: restore package
    #  run: |
    #    nuget sources add --source "https://nuget.pkg.github.com/Zina-420001498/index.json" --store-password-in-clear-text --username ${USERNAME} --password ${PAT}
    #   dotnet restore "PrimeService"
      #working-directory: ConsoleApp1
      #env:
      #  Password: ${{ secrets.PackagePAT }}
